[2024-07-24T03:50:18.012+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T03:50:18.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyTest.query_data_from_oracle manual__2024-07-24T03:50:16.279716+00:00 [queued]>
[2024-07-24T03:50:18.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyTest.query_data_from_oracle manual__2024-07-24T03:50:16.279716+00:00 [queued]>
[2024-07-24T03:50:18.043+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T03:50:18.055+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): query_data_from_oracle> on 2024-07-24 03:50:16.279716+00:00
[2024-07-24T03:50:18.063+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1235) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T03:50:18.064+0000] {standard_task_runner.py:64} INFO - Started process 1238 to run task
[2024-07-24T03:50:18.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'MyTest', 'query_data_from_oracle', 'manual__2024-07-24T03:50:16.279716+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/MyTest.py', '--cfg-path', '/tmp/tmpja5ng7py']
[2024-07-24T03:50:18.066+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask query_data_from_oracle
[2024-07-24T03:50:18.107+0000] {task_command.py:426} INFO - Running <TaskInstance: MyTest.query_data_from_oracle manual__2024-07-24T03:50:16.279716+00:00 [running]> on host ed4de24231fa
[2024-07-24T03:50:18.189+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MyTest' AIRFLOW_CTX_DAG_ID='MyTest' AIRFLOW_CTX_TASK_ID='query_data_from_oracle' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T03:50:16.279716+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T03:50:16.279716+00:00'
[2024-07-24T03:50:18.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T03:50:18.444+0000] {xcom.py:675} ERROR - Object of type bytes is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-07-24T03:50:18.451+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T03:50:18.452+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MyTest.py", line 96, in query_data_from_oracle
    ti.xcom_push(key='dataframe', value=pickle.dumps(df))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2024-07-24T03:50:18.464+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=MyTest, task_id=query_data_from_oracle, run_id=manual__2024-07-24T03:50:16.279716+00:00, execution_date=20240724T035016, start_date=20240724T035018, end_date=20240724T035018
[2024-07-24T03:50:18.488+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task query_data_from_oracle (Object of type bytes is not JSON serializable; 1238)
[2024-07-24T03:50:18.519+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T03:50:18.542+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T03:50:18.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
