[2024-07-24T04:12:20.995+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T04:12:21.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyTest.export_xlsx manual__2024-07-24T04:12:17.256588+00:00 [queued]>
[2024-07-24T04:12:21.028+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyTest.export_xlsx manual__2024-07-24T04:12:17.256588+00:00 [queued]>
[2024-07-24T04:12:21.028+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T04:12:21.040+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): export_xlsx> on 2024-07-24 04:12:17.256588+00:00
[2024-07-24T04:12:21.047+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1566) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T04:12:21.049+0000] {standard_task_runner.py:64} INFO - Started process 1569 to run task
[2024-07-24T04:12:21.049+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'MyTest', 'export_xlsx', 'manual__2024-07-24T04:12:17.256588+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/MyTest.py', '--cfg-path', '/tmp/tmpfk71r4sn']
[2024-07-24T04:12:21.050+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask export_xlsx
[2024-07-24T04:12:21.093+0000] {task_command.py:426} INFO - Running <TaskInstance: MyTest.export_xlsx manual__2024-07-24T04:12:17.256588+00:00 [running]> on host ed4de24231fa
[2024-07-24T04:12:21.186+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MyTest' AIRFLOW_CTX_DAG_ID='MyTest' AIRFLOW_CTX_TASK_ID='export_xlsx' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T04:12:17.256588+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T04:12:17.256588+00:00'
[2024-07-24T04:12:21.187+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T04:12:21.188+0000] {logging_mixin.py:188} INFO - <class 'str'>
[2024-07-24T04:12:21.200+0000] {logging_mixin.py:188} INFO - <class 'pandas.core.frame.DataFrame'>
[2024-07-24T04:12:21.209+0000] {logging_mixin.py:188} INFO -    PROSPECTID       PROSPECTFULLNAME  ...    SALETYPE  TEAMSTATUS
0          62        นายรวี สินบำรุง  ...     ต่ออายุ    Customer
1          61        นายรวี สินบำรุง  ...     ต่ออายุ    Customer
2          52     นายคาริวัล ทองโสภา  ...  ประกันใหม่    Customer
3          43  นางสาวนัทฎิชา สิริกุล  ...     ต่ออายุ    Customer
4          42  นางสาวนัทฎิชา สิริกุล  ...     ต่ออายุ    Customer
5          41          CompanyNameTH  ...     ต่ออายุ    Customer
6          23         นายทดสอบ ทดสอบ  ...     ต่ออายุ       Other
7          22  นายนันทิพัฒน์ ทวะบุรี  ...     ต่ออายุ    Customer
8          19  นายนันทวัฒน์ ข้าวสาลี  ...     ต่ออายุ    Customer
9          18         นายทดสอบ ทดสอบ  ...     ต่ออายุ    Customer

[10 rows x 7 columns]
[2024-07-24T04:12:21.210+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T04:12:21.211+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MyTest.py", line 121, in export_xlsx_func
    body += df
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 190, in __radd__
    return self._arith_method(other, roperator.radd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 7644, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 7676, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = b.apply(f, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 366, in apply
    result = func(self.values, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/roperator.py", line 11, in radd
    return right + left
           ~~~~~~^~~~~~
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U57'), dtype('int64')) -> None
[2024-07-24T04:12:21.225+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=MyTest, task_id=export_xlsx, run_id=manual__2024-07-24T04:12:17.256588+00:00, execution_date=20240724T041217, start_date=20240724T041221, end_date=20240724T041221
[2024-07-24T04:12:21.236+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 79 for task export_xlsx (ufunc 'add' did not contain a loop with signature matching types (dtype('<U57'), dtype('int64')) -> None; 1569)
[2024-07-24T04:12:21.263+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T04:12:21.280+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T04:12:21.282+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
