[2024-07-24T07:38:01.462+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T07:38:01.487+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyTest.send_email manual__2024-07-24T07:37:55.153265+00:00 [queued]>
[2024-07-24T07:38:01.495+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyTest.send_email manual__2024-07-24T07:37:55.153265+00:00 [queued]>
[2024-07-24T07:38:01.495+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T07:38:01.511+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_email> on 2024-07-24 07:37:55.153265+00:00
[2024-07-24T07:38:01.520+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4343) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T07:38:01.521+0000] {standard_task_runner.py:64} INFO - Started process 4346 to run task
[2024-07-24T07:38:01.521+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'MyTest', 'send_email', 'manual__2024-07-24T07:37:55.153265+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/MyTest.py', '--cfg-path', '/tmp/tmpa7esupmg']
[2024-07-24T07:38:01.522+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask send_email
[2024-07-24T07:38:01.566+0000] {task_command.py:426} INFO - Running <TaskInstance: MyTest.send_email manual__2024-07-24T07:37:55.153265+00:00 [running]> on host ed4de24231fa
[2024-07-24T07:38:01.734+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MyTest' AIRFLOW_CTX_DAG_ID='MyTest' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T07:37:55.153265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T07:37:55.153265+00:00'
[2024-07-24T07:38:01.735+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T07:38:01.747+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T07:38:01.748+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MyTest.py", line 143, in send_email_func
    body += df
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 190, in __radd__
    return self._arith_method(other, roperator.radd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 7644, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 7676, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = b.apply(f, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 366, in apply
    result = func(self.values, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/roperator.py", line 11, in radd
    return right + left
           ~~~~~~^~~~~~
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U57'), dtype('int64')) -> None
[2024-07-24T07:38:01.766+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=MyTest, task_id=send_email, run_id=manual__2024-07-24T07:37:55.153265+00:00, execution_date=20240724T073755, start_date=20240724T073801, end_date=20240724T073801
[2024-07-24T07:38:01.778+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task send_email (ufunc 'add' did not contain a loop with signature matching types (dtype('<U57'), dtype('int64')) -> None; 4346)
[2024-07-24T07:38:01.815+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T07:38:01.830+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T07:38:01.832+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
